"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, Clock3, Flame, Star, X } from "lucide-react";
import type { Workout } from "@/lib/workouts";
import { usePlan } from "@/context/PlanContext";

export default function PlanContent() {
  const { todayPlan, savedWorkouts, done, removeFromPlan, markDone, toggleSaved, isLoaded } = usePlan();
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<"plan" | "saved">("plan");
  const [notice, setNotice] = useState("");
  const tell = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2500); };
  useEffect(() => { fetch("/api/workouts").then((r) => { if (!r.ok) throw new Error(); return r.json() as Promise<Workout[]>; }).then(setWorkouts).catch(() => setWorkouts([])).finally(() => setLoading(false)); }, []);
  const ids = tab === "plan" ? todayPlan : savedWorkouts;
  const list = useMemo(() => ids.map((id) => workouts.find((workout) => workout.id === id)).filter((item): item is Workout => Boolean(item)), [ids, workouts]);
  const minutes = list.reduce((sum,item) => sum + item.duration, 0);
  const calories = list.reduce((sum,item) => sum + item.caloriesBurned, 0);
  return <main className="mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Plan your work. Work your plan.</p><h1 className="display-font mt-3 text-5xl font-extrabold uppercase sm:text-6xl">My <span className="text-lime">Plan</span></h1><p className="mt-3 text-sm text-zinc-400">Cap of five lifts for today. Finish them, then load more.</p></div><p className="rounded-full border border-white/10 px-4 py-2 text-xs text-zinc-400"><span className="text-lime">{todayPlan.length}</span> / 5 lifts planned</p></div>
    <div className="mt-9 grid grid-cols-3 gap-3 sm:gap-5">{[["Exercises",list.length,"◈"],["Minutes",minutes,"◷"],["Calories",calories,"⌁"]].map(([label,value,icon])=><div key={String(label)} className="rounded-xl border border-white/10 bg-white/[.025] p-4 sm:p-6"><div className="flex items-center justify-between"><span className="text-[9px] font-bold uppercase tracking-[.15em] text-zinc-500 sm:text-xs">{label}</span><span className="text-lime">{icon}</span></div><p className="display-font mt-2 text-3xl font-bold sm:text-4xl">{value}</p></div>)}</div>
    <div className="mt-12 flex items-center justify-between border-b border-white/10"><div className="flex gap-5"><button onClick={() => setTab("plan")} className={`tab-button ${tab === "plan" ? "tab-active" : ""}`}>Today&apos;s Plan <span>{todayPlan.length}</span></button><button onClick={() => setTab("saved")} className={`tab-button ${tab === "saved" ? "tab-active" : ""}`}>Saved <span>{savedWorkouts.length}</span></button></div><p className="hidden text-xs text-zinc-600 sm:block">{tab === "plan" ? "TODAY’S SESSION" : "YOUR BOOKMARKS"}</p></div>
    <section className="mt-6">{loading || !isLoaded ? <div className="py-16 text-center text-sm text-zinc-400"><span className="loading loading-spinner loading-sm mr-2 text-lime"/>Loading workouts…</div> : !list.length ? <div className="rounded-2xl border border-dashed border-white/15 px-5 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-white/[.05] text-xl text-zinc-500">＋</div><p className="eyebrow mt-5">Nothing here yet</p><p className="mt-2 text-sm text-zinc-500">Browse the library and add a lift to get today moving.</p><Link href="/#library" className="btn mt-6 h-11 border-0 bg-lime px-5 text-xs font-bold uppercase text-black">Go to workouts <ArrowUpRight size={15}/></Link></div> : <div className="space-y-3">{list.map((item) => <article key={item.id} className="flex flex-col gap-4 rounded-xl border border-white/10 bg-white/[.025] p-3 sm:flex-row sm:items-center sm:p-4"><Link href={`/workout/${item.id}`} className="relative h-32 overflow-hidden rounded-lg bg-white/5 sm:h-24 sm:w-36 sm:shrink-0"><Image src={item.image} alt={item.name} fill unoptimized sizes="150px" className="object-cover"/></Link><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{item.muscleGroups.slice(0,2).map((group)=><span className="tag" key={group}>{group}</span>)}{tab === "plan" && done.includes(item.id) && <span className="text-[9px] font-bold uppercase tracking-wider text-lime">Completed</span>}</div><Link href={`/workout/${item.id}`} className="display-font mt-2 block truncate text-xl font-bold uppercase hover:text-lime">{item.name}</Link><p className="mt-1 text-xs text-zinc-500">{item.equipment}</p><div className="mt-3 flex flex-wrap gap-4 text-[11px] text-zinc-400"><span className="flex items-center gap-1"><Clock3 size={13}/>{item.duration} min</span><span className="flex items-center gap-1"><Flame size={13}/>{item.caloriesBurned} kcal</span><span className="flex items-center gap-1 text-lime"><Star size={13} fill="currentColor"/>{item.rating}</span></div></div><div className="flex items-center gap-2 sm:flex-col lg:flex-row"><Link href={`/workout/${item.id}`} className="btn btn-sm flex-1 border-white/15 bg-transparent text-[10px] uppercase tracking-wider text-white hover:border-lime sm:flex-none">View details</Link>{tab === "plan" && <button disabled={done.includes(item.id)} onClick={() => {markDone(item.id); tell(`${item.name} marked as done`);}} className="btn btn-sm flex-1 border-0 bg-lime text-[10px] uppercase tracking-wider text-black hover:bg-[#d4ff56] disabled:bg-white/10 disabled:text-zinc-500 sm:flex-none"><Check size={14}/>Done</button>}<button aria-label={`Remove ${item.name}`} onClick={() => {tab === "plan" ? removeFromPlan(item.id) : toggleSaved(item.id); tell(`${item.name} removed`);}} className="btn btn-sm btn-square border-white/10 bg-transparent text-zinc-500 hover:border-red-400/40 hover:text-red-300"><X size={16}/></button></div></article>)}</div>}</section>
    {notice && <div role="status" className="toast toast-end toast-bottom z-50"><div className="alert border border-lime/20 bg-[#20231a] text-white"><span>{notice}</span></div></div>}</main>;
}
